services:
  backend:
    build:
      context: .
      dockerfile: build/go/Dockerfile
    container_name: gostd
    networks:
      - gostd-network
    ports:
      - "28080:8080"  # アプリケーションポート
      - "22345:2345"  # Delveデバッガーポート
    volumes:
      - .:/workspace
      - go-mod-cache:/go/pkg/mod
    environment:
      - CGO_ENABLED=0
    command: ["/bin/sh", "-c", "while true; do sleep 30; done"] # コンテナを永続化（Delve・Goアプリは手動制御）
    stdin_open: true
    tty: true

  postgres:
    container_name: db
    image: postgres:15-alpine
    ports:
      - '25432:5432'
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: Password123
      POSTGRES_DB: local_db
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: 'Asia/Tokyo'
    networks:
      - gostd-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser"]
      interval: 5s
      timeout: 5s
      retries: 5

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "28081:8080"
    environment:
      SWAGGER_JSON: /usr/share/nginx/html/swagger/openapi.yml
    volumes:
      - ./docs/swagger:/usr/share/nginx/html/swagger
    networks:
      - gostd-network

networks:
  gostd-network:
    driver: bridge

volumes:
  go-mod-cache: